#!/usr/bin/env bash
# test-precommit-hook.sh — il hook pre-commit e installato E aggiornato
#
# Estratto da test/validate.sh il 2026-07-31. Da qui si lancia anche da solo:
#   bash test/test-precommit-hook.sh
# che prima non si poteva: bisognava aspettare l'intera suite per leggere queste righe.
set -u
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT" || exit 1

FAIL=0
section() { printf "\n=== %s ===\n" "$1"; }
err() { printf "  FAIL: %s\n" "$1"; FAIL=1; }
ok()  { printf "  ok: %s\n" "$1"; }


section "pre-commit hook e' installato E aggiornato (il leak check blocca solo se e' acceso)"
# Nothing checked this until 2026-07-29, and on that day the installed hook was still the
# 2 July copy: hooks/pre-commit had been edited, the gate was green, and the new check had
# never run once. The leak check that BLOCKS commits lives in that same hook and was
# written after a real leak was committed and pushed — so "is it actually wired" is not
# hygiene, it is the control itself. A stale copy passes every other test in this file.
#
# The shim is matched on its GENERATED banner, not on the string "hooks/pre-commit": the
# first draft grepped for that path and passed on a stale COPY, because the copy carries
# it in its own header comment. Verified by putting the old copy back and watching this
# turn red — a check nobody has seen fail is a guess.
# `--git-path hooks/...` e non `--git-dir`/hooks: in un WORKTREE git-dir e'
# .git/worktrees/<nome>, dove gli hook non stanno mai — stanno nella common dir. Il gate
# era quindi rosso in ogni worktree, cioe' esattamente dove il piano dice di lavorare
# (`kb start` crea un worktree per card). Rosso sempre = spento, la stessa famiglia di
# difetti che questo controllo esiste per prendere. Stesso bug della board notice, che
# leggeva il repo padre da un worktree: chiedere a git DOVE guarda, non ricostruirlo.
_ih="$(git rev-parse --git-path hooks/pre-commit 2>/dev/null || true)"
if [ -z "$_ih" ] || [ ! -x "$_ih" ]; then
  # I git hook NON si clonano. Su una macchina di CI il hook non e' quindi assente per
  # negligenza: e' assente per costruzione, e non controlla comunque niente perche' la CI
  # non committa. Trattarlo come errore ha reso rossa la CI di main dal merge di PR #30 —
  # cioe' un gate sempre rosso, che e' un gate spento, che e' esattamente la famiglia di
  # difetti per cui questo controllo era stato scritto. Trovato da @thor su clone pulito.
  # Sulla macchina di Roberto resta un ERRORE, perche' li' e' l'unico posto dove serve.
  if [ -n "${CI:-}" ]; then
    ok "nessun pre-commit installato, ma siamo in CI: li' non committa nessuno"
  else
    err "nessun pre-commit installato — il leak check non blocca niente (bash bin/install-git-hooks.sh)"
  fi
elif grep -q '^# GENERATED by bin/install-git-hooks.sh' "$_ih" 2>/dev/null; then
  ok "pre-commit e' uno shim sul file versionato: non puo' andare fuori sincrono"
elif diff -q hooks/pre-commit "$_ih" >/dev/null 2>&1; then
  ok "pre-commit e' una copia, ma identica al sorgente"
else
  err "il pre-commit installato NON e' il sorgente versionato: le modifiche a hooks/pre-commit non hanno effetto (bash bin/install-git-hooks.sh)"
fi
unset _ih


[ "$FAIL" -eq 0 ] && { echo; echo "test-precommit-hook: PASS"; exit 0; }
echo; echo "test-precommit-hook: FAIL"; exit 1
