#!/usr/bin/env bash
# evolve/watch.sh — weekly watcher: detects novelties in tool changelogs and, per novelty,
# DROPS A KANBAN CARD any agent (Claude, Copilot, …) can pick up and execute on its next run.
# It does NOT analyze itself and NEVER launches a headless agent — the card IS the handoff
# (Roberto's choice: no `claude -p`, use the kanban dispatch pattern). Never applies to the
# canon. Durable state in seen (flat KEY=FP). See evolve/evolve-protocol.md.
# Launched by launchd com.roberdan.rda-evolve. Idempotent, non-blocking.
set -euo pipefail

RDA_HOME="${RDA_HOME:-$HOME/.roberdan-os}"
state_dir="${RDA_EVOLVE_STATE:-$RDA_HOME/evolve}"
repo_root="$(git -C "$(dirname "$0")" rev-parse --show-toplevel 2>/dev/null || echo "$HOME/GitHub/roberdan-os")"
# Cards land in the kanban todo column (gitignored, local-only). Overridable for tests so a
# run never dirties the real board.
kb_todo="${RDA_KANBAN_TODO:-$repo_root/kanban/todo}"
seen="$state_dir/seen"            # flat: one line "name=sha256" per source
mkdir -p "$state_dir" "$kb_todo"
touch "$seen"

# Sources: name → changelog URL (versioned). Expandable.
sources_names=(claude-code copilot codex hermes-agent warp)
sources_urls=(
  "https://docs.anthropic.com/en/release-notes/claude-code"
  "https://github.blog/changelog/label/copilot/"
  "https://github.com/openai/codex/releases"
  "https://github.com/NousResearch/hermes-agent/releases"
  "https://docs.warp.dev/getting-started/changelog"
)

now="$(date +%Y-%m-%d)"
new_count=0

for i in "${!sources_names[@]}"; do
  name="${sources_names[$i]}"; url="${sources_urls[$i]}"
  body="$(curl -fsSL --max-time 20 "$url" 2>/dev/null || true)"
  [ -n "$body" ] || { echo "watch: $name unreachable, skip" >&2; continue; }

  # Content fingerprint: a change = possible novelty. The capability-diff is done
  # by an agent on the draft; here we only detect the delta.
  fp="$(printf '%s' "$body" | shasum -a 256 | cut -d' ' -f1)"
  prev="$(awk -F= -v k="$name" '$1==k{print $2}' "$seen" 2>/dev/null || true)"
  [ "$fp" = "$prev" ] && continue

  new_count=$((new_count+1))
  # One card per novel source. Id is timestamped AND suffixed with the source name so two
  # changelogs changing in the same second don't collide on the id. Frontmatter matches the
  # kb schema (title, repo, dod, acceptance, status, created) that test/validate.sh lints.
  card_id="$(date +%y%m%d-%H%M%S)-${name}"
  card="$kb_todo/${card_id}.md"
  {
    echo '---'
    echo "title: \"evolve: analyze $name updates and propose optimizations for roberdan-os\""
    echo "repo: roberdan-os"
    echo "dod: \"Concrete $name novelties extracted (version + date) from the changelog; impact on roberdan-os assessed (hook/skill/agent/scheduling/MCP/memory/factory/loop); proposal written to proposals/${now}-${name}.md with source citation. Draft-only: no change to behavior/rules/agents/AGENTS.md.\""
    echo "acceptance: \"proposals/${now}-${name}.md exists with novelties + impact + suggested patch and the source URL/version/date cited; the canon is untouched.\""
    echo 'status: todo'
    echo "created: $now"
    echo '---'
    echo
    echo "**Auto-generated by the evolve watcher** ($now) — \`$name\`'s changelog changed since the last scan."
    echo
    echo "Source: $url"
    echo
    # Rejected-proposal buffer: what was already assessed and declined for THIS source, so the
    # agent doesn't re-derive it a fourth week running (see evolve/declined.sh for the measured
    # case this exists for). Informational — it never suppresses a genuine novelty.
    if declined_block="$("$(dirname "$0")/declined.sh" render "$name" 2>/dev/null)" && [ -n "$declined_block" ]; then
      echo "**Already assessed and DECLINED for \`$name\`** — do not re-propose these unless the"
      echo "source shows something materially new about them; say explicitly that you skipped them:"
      echo
      printf '%s\n' "$declined_block"
      echo
    fi
    echo "Task for whichever agent picks this card up (any CLI — Claude, Copilot):"
    echo "1. Open the source; identify the concrete novelties since the last known version (with version + date)."
    echo "2. For each, assess whether it touches something roberdan-os uses (hook, skill, agent, scheduling, MCP, memory, factory, loop)."
    echo "3. Write the proposal to \`proposals/${now}-${name}.md\`: what changes, why, the suggested patch — **with source citation (URL + version + date)**. No citation → no proposal."
    echo "4. Do NOT apply to the canon: draft-only, human gate (see evolve/evolve-protocol.md)."
    echo "5. For every novelty you assess and decide needs NO patch, record it so next week's card"
    echo "   carries it forward: \`evolve/declined.sh add $name \"<one-line summary>\"\`."
  } > "$card"
  echo "watch: NEW card → $card" >&2

  # Atomically update seen: remove the old line, add the new one.
  grep -v "^${name}=" "$seen" > "$seen.tmp" 2>/dev/null || true
  printf '%s=%s\n' "$name" "$fp" >> "$seen.tmp"
  mv "$seen.tmp" "$seen"
done

echo "watch: $new_count novelties → $new_count kanban card(s) in $kb_todo (run \`kb\` to see them)" >&2
